server:
  port: 80

county: china

user:
  name: itcast
  age: 16

a:
  b:
    c:
      name: abc


likes: [age,music,sleep]


user1: [{name: zhangsan,age: 16},{name: lisi,age: 16}]

user2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 16

#  应用
baseDir: c:\windows

tempDir: ${baseDir}\temp


#创建类，用于封装下面的数据
#有spring帮我们去加载数据到对象中，一定要告诉spring加载这组信息
#使用时候从spring中直接获取信息使用
datasource:
  driver: com.mysql.jdbc.driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: 123